name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    
    - name: Download dependencies
      run: go mod download
    
    - name: Run go fmt
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "The following files are not formatted:"
          gofmt -s -l .
          exit 1
        fi
    
    - name: Run go vet
      run: go vet ./hcas/... ./hcasfs/...
    
    - name: Run tests
      run: go test -v ./hcas/... ./hcasfs/...
    
    - name: Build binaries
      run: |
        go build -o bin/main ./cmd/main.go
        go build -o bin/import ./cmd/import.go
        go build -o bin/fuse ./cmd/fuse.go
        go build -o bin/gc ./cmd/gc.go
    
    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-binaries
        path: bin/
